In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
# Retina mode
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import torch
from torchvision import datasets, transforms
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, ConfusionMatrixDisplay

## Full Batch GD

In [ ]:
num_samples = 40
np.random.seed(45)

# Generate data
x1 = np.random.uniform(-20, 20, num_samples)
f_x = 100*x1 + 1
eps = np.random.randn(num_samples)
y = f_x + eps
print(x1.shape,y.shape)

(40,) (40,)


In [4]:
theta=torch.randn((2,1),requires_grad=True)

x=torch.tensor(x1,dtype=torch.float32).view(-1, 1)       #reshape is same as view
x=torch.cat((torch.ones(x.shape[0],1),x), dim=1)
y =torch.tensor(y, dtype=torch.float32).view(-1, 1)
theta_hist=[]
loss_hist=[]
learning_rate=0.001
beta = 0.08
v_t = torch.zeros_like(theta)
Epoch=0
while(True):
    Epoch+=1
    theta_old=theta.clone()
    theta_hist.append(theta_old.detach().numpy().flatten())
    y_pred=torch.matmul(x,theta)
    loss=torch.mean((y-y_pred)**2)
    loss_hist.append(loss.clone().detach().item())
    loss.backward()       # As soon as you alled the backward func in the loss it calculates the grad  of loss wrt defined var which has req_grad=True and stores in the defined var.grad
    with torch.no_grad():
        v_t = beta*v_t + (1-beta)*theta.grad
        theta-=learning_rate*v_t
        theta.grad.zero_()
    
    # Print every 50 epochs
    if Epoch % 50 == 0:
        print(f"Step {Epoch}, Loss: {loss.item():.6f}, theta:\n{theta}")
        
    if(torch.norm(theta-theta_old)<0.001):
        break

print(Epoch) 
# print(loss_hist)

Step 50, Loss: 2.998015, theta:
tensor([[-0.6141],
        [99.9630]], requires_grad=True)
Step 100, Loss: 2.571156, theta:
tensor([[-0.4682],
        [99.9649]], requires_grad=True)
Step 150, Loss: 2.220127, theta:
tensor([[-0.3360],
        [99.9667]], requires_grad=True)
Step 200, Loss: 1.931480, theta:
tensor([[-0.2161],
        [99.9683]], requires_grad=True)
Step 250, Loss: 1.694118, theta:
tensor([[-0.1074],
        [99.9698]], requires_grad=True)
Step 300, Loss: 1.498946, theta:
tensor([[-8.7614e-03],
        [ 9.9971e+01]], requires_grad=True)
Step 350, Loss: 1.338449, theta:
tensor([[8.0651e-02],
        [9.9972e+01]], requires_grad=True)
Step 400, Loss: 1.206471, theta:
tensor([[ 0.1617],
        [99.9735]], requires_grad=True)
Step 450, Loss: 1.097956, theta:
tensor([[ 0.2353],
        [99.9745]], requires_grad=True)
Step 500, Loss: 1.008714, theta:
tensor([[ 0.3019],
        [99.9753]], requires_grad=True)
Step 550, Loss: 0.935336, theta:
tensor([[ 0.3624],
        [99.976

In [5]:
np.random.seed(45)
num_samples = 40
    
# Generate data
x1 = np.random.uniform(-1, 1, num_samples)
f_x = 3*x1 + 4
eps = np.random.randn(num_samples)
y = f_x + eps

In [11]:
theta=torch.randn((2,1),requires_grad=True)

x=torch.tensor(x1,dtype=torch.float32).view(-1, 1)       #reshape is same as view
x=torch.cat((torch.ones(x.shape[0],1),x), dim=1)
y =torch.tensor(y, dtype=torch.float32).view(-1, 1)
theta_hist=[]
loss_hist=[]
learning_rate=0.001
beta = 0.08
v_t = torch.zeros_like(theta)
Epoch=0
while(True):
    Epoch+=1
    theta_old=theta.clone()
    theta_hist.append(theta_old.detach().numpy().flatten())
    y_pred=torch.matmul(x,theta)
    loss=torch.mean((y-y_pred)**2)
    loss_hist.append(loss.clone().detach().item())
    loss.backward()       # As soon as you alled the backward func in the loss it calculates the grad  of loss wrt defined var which has req_grad=True and stores in the defined var.grad
    with torch.no_grad():
        v_t = beta*v_t + (1-beta)*theta.grad
        theta-=learning_rate*v_t
        theta.grad.zero_()
    
    # Print every 50 epochs
    if Epoch % 50 == 0:
        print(f"Step {Epoch}, Loss: {loss.item():.6f}, theta:\n{theta}")
        
    if(torch.norm(theta-theta_old)<0.001):
        break

print(Epoch) 
# print(loss_hist)

C:\Users\siddh\AppData\Local\Temp\ipykernel_8904\446197366.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y =torch.tensor(y, dtype=torch.float32).view(-1, 1)


Step 50, Loss: 5.280635, theta:
tensor([[1.7822],
        [1.6237]], requires_grad=True)
Step 100, Loss: 4.487941, theta:
tensor([[1.9803],
        [1.6394]], requires_grad=True)
Step 150, Loss: 3.836557, theta:
tensor([[2.1597],
        [1.6561]], requires_grad=True)
Step 200, Loss: 3.300832, theta:
tensor([[2.3221],
        [1.6738]], requires_grad=True)
Step 250, Loss: 2.859797, theta:
tensor([[2.4692],
        [1.6922]], requires_grad=True)
Step 300, Loss: 2.496313, theta:
tensor([[2.6024],
        [1.7112]], requires_grad=True)
Step 350, Loss: 2.196368, theta:
tensor([[2.7231],
        [1.7307]], requires_grad=True)
Step 400, Loss: 1.948506, theta:
tensor([[2.8325],
        [1.7505]], requires_grad=True)
Step 450, Loss: 1.743354, theta:
tensor([[2.9316],
        [1.7706]], requires_grad=True)
Step 500, Loss: 1.573249, theta:
tensor([[3.0214],
        [1.7908]], requires_grad=True)
Step 550, Loss: 1.431924, theta:
tensor([[3.1028],
        [1.8111]], requires_grad=True)
Step 600, L